In [1]:
import pandas as pd

In [2]:
d1 = pd.read_csv(r"C:\\Users\\ar543\\AppData\\Local\\Packages\\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\\LocalState\\sessions\\26FF86840ACE092E94CDDBB8F1A7D6230CF7C35F\\transfers\\2026-20\\delivery_time.csv")

In [3]:
d1

    Delivery_Time  Sorting_Time
0           21.00            10
1           13.50             4
2           19.75             6
3           24.00             9
4           29.00            10
5           15.35             6
6           19.00             7
7            9.50             3
8           17.90            10
9           18.75             9
10          19.83             8
11          10.75             4
12          16.68             7
13          11.50             3
14          12.03             3
15          14.88             4
16          13.75             6
17          18.11             7
18           8.00             2
19          17.83             7
20          21.50             5

In [4]:
d1.head()

   Delivery_Time  Sorting_Time
0          21.00            10
1          13.50             4
2          19.75             6
3          24.00             9
4          29.00            10

In [5]:
from matplotlib import pyplot as plt

In [7]:
plt.scatter(d1['YearsExperience'],d1['Salary'])
plt.xlabel("YearsExpeience")
plt.ylable("Salary")
plt.show()

KeyError: 'YearsExperience'

NameError: name 'slr' is not defined

In [13]:
from sklearn.linear_model import LinearRegression

In [15]:
slr = LinearRegression()

In [16]:
slr.fit(x,y) #model training

NameError: name 'x' is not defined

In [17]:
y_pred = slr.predict(x)

NameError: name 'x' is not defined

In [18]:
y_pred.roond(2)

NameError: name 'y_pred' is not defined

In [19]:
slr.coef_

AttributeError: 'LinearRegression' object has no attribute 'coef_'

slr.intercept_

In [ ]:
error=y-y_pred

In [20]:
from sklearn.metrics import r2_score,mean_squared_error

In [21]:
r2_score(y,y-pred)

NameError: name 'y' is not defined

In [22]:
mean_squared_error(y,y_pred)

NameError: name 'y' is not defined